# name: Python application - create and push docker image - 2

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# permissions:
#   contents: read

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Log in to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: ./real_estate_bot
    #     push: true
    #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/real_state:latest

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: Installing buildx to create image arm64
      run: docker buildx create --use

    - name: Build the Docker image and push to repo
      run: docker buildx build . --file Dockerfile --platform linux/arm64 --tag ${{ secrets.DOCKER_HUB_USERNAME }}real_state:latest --push
    
    # - name: push to Docker hub
    #   run: docker tag real_state:latest ${{ secrets.DOCKER_HUB_USERNAME }}/real_state:latest